name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend
      run: |
        docker build -f ./backend/crud-dockfile -t ${{ secrets.DOCKER_USERNAME }}/mean-backend:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/mean-backend:latest

    - name: Build and push frontend
      run: |
        docker build -f ./frontend/crud-dockerfile -t ${{ secrets.DOCKER_USERNAME }}/mean-frontend:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/mean-frontend:latest

    - name: Deploy to VM via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VM_HOST }}
        username: ubuntu
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd ~/mean-crud-app
          git pull origin main
          docker-compose pull
          docker-compose up -d